### ISSUE TITLE
Tracking issue from PO Discussion

### ISSUE THREAD

**Issue by ethanfrey** [osmosis-labs/isotonic#63]
Ready to work on:

- [x] New interest rate model (compound v2 with target rate) See https://github.com/confio/lendex/issues/64
- [x] Add limits to lending/borrowing per market  See https://github.com/confio/lendex/issues/65
- [x] Add reserve to each market: See https://github.com/confio/lendex/issues/47

Open questions:

- [ ]  Add governance control of contracts (Possible use of sudo / on-chain governance)? See https://github.com/confio/lendex/milestone/4
- [x] Allow list for who can liquidate with governance control? (unsure, discuss with Osmosis) https://github.com/confio/lendex/issues/66
- [ ] Payout bonus with constant APR (as another distribution contract or Osmosis Go code?)

Osmosis Specific (need custom bindings)
- [x] Price oracle using TWAP. See https://github.com/confio/lendex/issues/67
- [x] Liquidate via AMM ?? See https://github.com/confio/lendex/issues/68
- [ ] Emit LTokens as native tokens (probably v2?) See https://github.com/confio/lendex/issues/70

v2:

handle staked tokens... we should prepare to accept cw20 as well as native tokens https://github.com/confio/lendex/issues/69
